export const GAME_CONSTANTS = {
    LANE_COUNT: 5,
    INITIAL_SPEED: 2.5,
    MAX_SPEED: 6.0,
    INITIAL_LIVES: 3,
    INVINCIBILITY_DURATION: 2000,
    RESPAWN_INVINCIBILITY_DURATION: 1500,
    SCORE_PER_NEAR_MISS: 100,
    COMBO_MULTIPLIER_STEP: 5,
    MAX_MULTIPLIER: 5,
    REST_SCREEN_TRIGGER_TIME: 60, // seconds
    DIFFICULTY_SPEED_INCREMENT: 0.1,
    DIFFICULTY_SCORE_STEP: 500,
    CANVAS_TARGET_WIDTH: 450,
    CANVAS_WIDTH_RATIO: 0.7,
    ROAD_SCROLL_SPEED_MULTIPLIER: 3,
    ENEMY_SPEED_MULTIPLIER: 2,
    TIME_STEP: 16, // ms
    SCORE_TIME_FACTOR: 0.5,
} as const;

export const STORAGE_KEYS = {
    HIGH_SCORE: "traffic_game_highscore",
    HIGH_SCORES_LIST: "conduce-seguro-highscores"
} as const;
